class Function:
    def __init__(self):
        ...

    def __call__(self, *args):
        ...

    def diff(self, *args, variable):
        ...

    def __add__(self, other):
        ...

    def __sub__(self, other):
        ...

    def __pow__(self, power, modulo=None):
        ...

    def __mul__(self, other):
        ...

    def __rmul__(self, other):
        ...

    def __truediv__(self, other):
        ...
